title: Avery's Website
author: Avery Chen
email: achen13@ebnet.org
description: > # this means to ignore newlines until "baseurl:"
  Here is a little about me:

# social links
instagram_username: averychn # DO NOT include the @ character, or else the build will fail!
github_username:  averychen13 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
